def publishedGroup = providers.gradleProperty("wasmtime.android.group").get()
def publishedVersion = providers.gradleProperty("wasmtime.android.version").get()
def artifactId = ext["wasmtime.publishedArtifactId"]
def pomName = ext["wasmtime.publishedName"]
def pomDescription = ext["wasmtime.publishedDescription"]

mavenPublishing {
    coordinates(publishedGroup, artifactId, publishedVersion)
    pom {
        name = pomName
        description = pomDescription
        inceptionYear = "2026"
        url = "https://github.com/fenriliuguang/wasmtime-android-kt"
        licenses {
            license {
                name = "Apache License, Version 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "repo"
            }
        }
        developers {
            developer {
                id = "fenriliuguang"
                name = "焚日流光"
                url = "https://github.com/fenriliuguang"
            }
        }
        scm {
            url = "https://github.com/fenriliuguang/wasmtime-android-kt"
            connection = "scm:git:git://github.com/fenriliuguang/wasmtime-android-kt.git"
            developerConnection = "scm:git:ssh://git@github.com/fenriliuguang/wasmtime-android-kt.git"
        }
    }
}
